### ISSUE TITLE
Can't centre "Click CEOP" button

### ISSUE THREAD

**Issue by spruce10** [JackFurby/Bootscout#30]
I'm trying to centre the Internet Safety button, to line up with everything else in the footer. Is this possible, eg with some CSS in the theme customiser if there's no specific option available?

**Comment by JackFurby** [comment]
Hi @spruce10, that is not built into the theme but you are welcome to add it yourself. To help you out, the button is located in the file functions/hooks.php on line 186 to 188. You could possibly use a class from [Bootstrap](https://getbootstrap.com/) or write your own CSS. The div element containing the button has the id `ceop` which can be used to target it with any CSS you add.
