### ISSUE TITLE
Ninja Forms not working

### ISSUE THREAD

**Issue by MBayley** [JackFurby/Bootscout#31]
I have made sure that WordPress and all plugins are up to date as well as having version 1.6.4 of the theme. Ninja Forms no longer loading on pages (since update to Ninja Forms plugin). I don't know if this is a theme issue or some other issue.

**Comment by MBayley** [comment]
I have just been through rolling back Ninja Form versions - the last working version is 3.6.9. The current version (3.6.11) of Ninja Forms works on other themes so think it must be a clash with the theme.

**Comment by JackFurby** [comment]
Hi @MBayley,

I think this is an issue not related to the theme. I have installed the theme onto my local site and a live website I manage and in both instances I was able to load the test form Ninja Forms provides. I could not see anything that would have caused this in regards to the recent updates with Ninja Forms but looking at their support page it appears this is a common issue ([https://wordpress.org/support/topic/ninja-forms-not-loading/](https://wordpress.org/support/topic/ninja-forms-not-loading/)).

hopefully you can resolve the issue soon or Ninja Forms releases a fix.
