### ISSUE TITLE
Theme possibly interferring with WP Forms buttons

### ISSUE THREAD

**Issue by jstarj010101** [JackFurby/Bootscout#48]
Hi. I'm using WP Forms and Bootscout. The radio buttons and checkbox on the forms aren't selectable. I've added some CSS to fix the issue but you may want to take a look. Described here: https://wordpress.org/support/topic/cant-select-radio-button-on-form/

https://sunningdalescouts.org.uk/wp/get-involved/apply-to-join-a-section/

**Comment by JackFurby** [comment]
Apologies for not replying sooner, I have a fix for this and will look to release it this weekend.

**Comment by JackFurby** [comment]
An update addressing this issue is available in release 2.0.4. In order to use WPForms please follow the following steps 

1. From the WordPress dashboard navigate to WPForms -> Settings
2. Select `base styling only` from the drop down selection Include Form Styling
3. Save settings
