### ISSUE TITLE
WooCommerce

### ISSUE THREAD

**Issue by benjamin-v1** [JackFurby/Bootscout#52]
Hey Jack 👋 - Love the theme, it has saved me a huge amount of time. I wonder if you could help out, I was just wondering if you had ever used WooCommerce with your theme. I am having a go and am seeing some strange behavior with form elements:

![image](https://user-images.githubusercontent.com/114483383/227019666-84bec508-9a16-4273-b29c-93416300a022.png)

Feel free to tell me to go away, but i thought its worth an ask :)

**Comment by JackFurby** [comment]
Hi Ben,

I have not looked at WooCommerce before but I'll be happy to see if there is something I can do. I cannot promise a time frame to have a fix out but as long as there are no surprises, it should not take more than a few weeks.

**Comment by benjamin-v1** [comment]
Thanks, Jack - Happy to help in any way I can, saying that its been a long time since I messed around with WordPress themes, and the block-based stuff is hurting my head 🤷‍♂️

**Comment by JackFurby** [comment]
Hi Ben,

Thought I'd provide a small update. I have figured out what is causing the layout issue but the fix will require remaking styling for the entire WooCommerce plugin, and as such it will take longer than I initially expected. Hopefully I'll be able to get a fix out soon but I have to work around some deadlines at my day job so don't know when this will be. You are welcome to give the fix a go yourself and I'll make a branch with the changes I've made so far as a starting point.

**Comment by benjamin-v1** [comment]
Cheers Jack - appreciate you taking the time to look. If you can publish a branch that would be great, as I said it been a lot of time since I messed around with templates but if it's just a case of working along what you have already done I will have a go :) My GSL wants me to go live next week, but it might have to be a a little off to start with 😂
________________________________

**Comment by JackFurby** [comment]
Hi Ben,

The branch is now up. You may also find the development environment set-up useful in this repo's wiki.

**Comment by JackFurby** [comment]
Hi Ben,

I have completed a fix for the issue with woocommerce and attached the updated theme to this comment. Feel free to try this. I will push out an update to the main theme soon but I know of a few bugs that will need to be fixed before I can do that.

[bootscout.zip](https://github.com/JackFurby/Bootscout-theme/files/11642444/bootscout.zip)

**Comment by JackFurby** [comment]
This issues was addressed in release 2.1
