### ISSUE TITLE
Single post formatting error.

### ISSUE THREAD

**Issue by HewittRDS** [JackFurby/Bootscout#71]
When using the following plugins the single post template becomes corrupted.

Wired Impact Volunteer Management
Volunteer manager and Store locator from https://2ndnewhawscouts.org.uk/wordpress-plugins-for-scout-websites/
WP Store Locator

Issues can be seen here https://ryedaledistrictscouts.org.uk/volunteer-opportunity/squirrels-drey-leader

**Comment by HewittRDS** [comment]
I have subsequently spoken with all of the providers of the other plugins I use and they have all pointed to the issue being the theme not supporting "custom post types"

**Comment by HewittRDS** [comment]
Accidentally closed - information from plugin dev

The volunteer system primarily uses the styles provided by the theme. There are a few possible causes to the issue here:

 - The website's theme doesn't support what are called "custom post types" which includes volunteer opportunities.

 - There is a plugin in place that limits the styling for volunteer opportunities.

As a first step I'd recommend reaching out for help from the Bootscout theme's developers. Based on their website it looks like you can do that at https://github.com/JackFurby/Bootscout-theme/issues.

Let us know if we can help clarify how the volunteer system works, and what's needed to ensure everything is compatible.

Post Link: https://wordpress.org/support/topic/theme-issue-37/#post-17554419

**Comment by JackFurby** [comment]
Hi @HewittRDS,

What version of the theme are you using? You can find this in Appearance->Themes->Bootscout-theme.

Also, if you could also detail any options you are setting in the plugin or when creating a volunteering opportunity. Hopefully I'll be able to reproduce this on my end with that information and get a fix out. 

Kind regards,
Jack

**Comment by HewittRDS** [comment]
Hi Jack,

The theme is the latest version (2.4.1)

As for setting all are completely out of the box and these are the exact plugins in use.

SFL WIVM Extender v1.5 by David Breakwell and I have spoken with him, nothing in those plugins is causing the issue.

Wired Impact Volunteer Management 2.4 by Wired Impact, they have said it is happening because the these doesn't support Custom Post Type.

I hope this helps.



Kind Regards,
Mike - Ryedale District Support Team Member / 1st Kirkbymoorside Scout Troop Team Member
[signatureImage]
________________________________

**Comment by JackFurby** [comment]
Hi Mike,

Thank you for your reply about the theme and plugin configuration. Unfortunately, I have not been able to reproduce the issue on both my development site and a live site. I have included a screenshot below showing how volunteer opportunities are displayed on my end. Here are two troubleshooting steps I would take which might resolve your issue:

1. Re-install Wired Impact Volunteer Management plugin in case something went wrong when installing it the first time
2. Disable installed plugins one at a time until Volunteer Management works. If this fixes how volunteer opportunities are displayed then the last plugin you disabled is the cause of the issue.

I will continue to dig around a bit in case I missed something and will get back to you if anything changes.

Kind regards,
Jack

![Screenshot 2024-04-06 at 15-27-34 Test opportunity – Bootscout](https://github.com/JackFurby/Bootscout-theme/assets/22617974/e0610ceb-8514-47a1-bd39-a22b16c935bf)

**Comment by HewittRDS** [comment]
So I have disabled all plugins and started again and yep the theme works perfectly right until I install the SFL WIVM Extender. Did you have it installed on your test build?


Kind Regards,
Mike - Ryedale District Support Team Member / 1st Kirkbymoorside Scout Troop Team Member
[signatureImage]
________________________________

**Comment by JackFurby** [comment]
Hi Mike,

Thank you for checking that. The SFL WIVM extender plugin also causes the issue on my end. I get the error message `Deprecated: File Theme without header.php is deprecated since version 3.0.0 with no alternative available`. It looks like this error message is raised when a plugin does not support block themes (such as Bootscout).

Unfortunately, this cannot be resolved by updating the theme and would require an update to the SFL WIVM extender plugin. I have briefly looked at their code, but I am not too familiar with plugin development so I cannot provide much help there.

I will close this issue now, but you can reopen it if you have anything new to add, or open a new issue if you have an unrelated problem with the theme.

Kind reagrds,
Jack

**Comment by HewittRDS** [comment]
The developer just asked me to change a file name to do_not_use_single-volunteer_opp.php in the plugin and report back so doing it now.


Kind Regards,
Mike - Ryedale District Support Team Member / 1st Kirkbymoorside Scout Troop Team Member
[signatureImage]
________________________________

**Comment by HewittRDS** [comment]
Deleted the file instead of renaming it and the issue disappeared.

Thanks for your help in resolving/identifying the issue.

**Comment by JackFurby** [comment]
Hi Mike,

I have just released a new update (2.4.3), which adds a few styling changes for WIVM and might be of interest to you.

Kind regards,
Jack

**Comment by HewittRDS** [comment]
I've done the update and yes it looks better now, I also got the other plugin working by deleting that file and then adding a couple of spaces in the PHP file and two headers.

This is how it looks now with everything running
https://ryedaledistrictscouts.org.uk/volunteer-opportunity/squirrels-team-member

I also run the theme on the 1st Kirkbymoorside site too in standard form and it looks fantastic 😊 that is Https://1stkirkbymoorsidescouts.org.uk


Kind Regards,
Mike - Ryedale District Support Team Member / 1st Kirkbymoorside Scout Troop Team Member
[signatureImage]
________________________________

**Comment by jg314** [comment]
Thanks so much for improving support for our volunteer management plugin @JackFurby. We really appreciate it!
